services:
  db:
    # Usamos la imagen oficial de PostgreSQL (etiqueta fija)
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    # B2: Persistencia de datos mediante un volumen
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Reto 2: Control de salud para saber cuándo la BD está realmente lista
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    # Reto 4: La BD solo vive en la red interna (roja)
    networks:
      - backend

  api:
    build:
      context: ./api
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DB_HOST
    # Reto 2: La API espera a que el healthcheck de la BD diga "healthy"
    depends_on:
      db:
        condition: service_healthy
    # Reto 4: La API es el puente, se conecta a ambas redes
    networks:
      - frontend
      - backend
  
  web:
    build:
      # El contexto es la raíz para que pueda ver el index.html
      context: .
      dockerfile: web/Dockerfile
    restart: always
    # Exponemos el puerto 8080 hacia tu computadora
    ports:
      - "8080:8080"
    depends_on:
      - api
    # Reto 4: Web solo pertenece a la red frontend, no puede ver a la base de datos
    networks:
      - frontend

# Declaramos el volumen para que los mensajes persistan
volumes:
  pgdata:

# Reto 4: Red segmentada (Nadie desde afuera puede tocar el backend)
networks:
  frontend:
  backend: