server {
    # Nginx sin privilegios usa puertos altos (8080) en lugar del 80
    listen 8080;
    server_name localhost;

    # Sirve los archivos estáticos de tu perfil
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Proxy inverso: Redirige todo lo que vaya a /api/ hacia el contenedor "api"
    location /api/ {
        proxy_pass http://api:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}